name: eifp
favicon: null
layout_spectrum: 0.29885437339544296
typography_spectrum: 0.6884046744089574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.16377886501140893
  lightness: 0.5992593776900321
  saturation: 0.16746912035159767
  rhythmicContrast: 0.1891521045472473
purpose: []
